name: Build Website
on: [push]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: checkout repo files
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          npm install
          npm install -g gatsby-cli

      - name: build project with gatsby cli
        run: gatsby build

      - name: artifact public folder
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public/

  Test-Artifact:
    runs-on: ubuntu-latest
    container: alpine
    needs: Build-Website
    steps:
      - name: recover artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public/

      - name: test build
        run: |          
          grep -q "Gatsby" ./public/index.html

  Test-Website:
    runs-on: ubuntu-latest
    container: node
    needs: Build-Website
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: recover artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public/            

      - name: install dependencies
        run: |
          npm install
          npm install -g gatsby-cli

      - name: test application
        run: |
          gatsby serve &
          sleep 3
          curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

  Deploy-Website:
    runs-on: ubuntu-latest
    needs:
      - Test-Artifact
      - Test-Website
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public/
        
      - name: install surge depedency
        run: npm install --global surge

      - name: publish production build
        run: surge --project ./public/ --domain lgm-github-static.surge.sh
        