name: Build Website
on: [push]
jobs:
  Build-Website:
    runs-on: ubuntu-latest
    container: node
    steps:
      - name: checkout repo files
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: install gatsby cli globally
        run: npm install -g gatsby-cli

      - name: build project with gatsby cli
        run: gatsby build

      - name: artifact public folder
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public/

  Test-Artifact:
    runs-on: ubuntu-latest
    needs: Build-Website
    steps:
      - name: recover artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: ./public/

      - name: test build
        run: |
          ls
          grep "Gatsby" ./public/index.html
          grep "Gata1sf56a1s56fas5sby" ./public/index.html

